In [1]:
import numpy as np 

In [68]:
import numpy as np

data = np.array([
    [101, 25, 50000, 2000, 4.5],
    [102, 30, 60000, 5000, 3.8],
    [103, 22, 45000, 1000, 4.2],
    [104, 28, 52000, 3000, 4.0],
    [105, 35, 75000, 7000, 3.5],
    [106, 26, 48000, 1500, 4.7],
    [107, 40, 80000, 10000, 3.9],
    [108, 29, 58000, 4000, 4.3]
    #[ID, Age, Salary, Bonus, Rating]
])
data

array([[  101. ,    25. , 50000. ,  2000. ,     4.5],
       [  102. ,    30. , 60000. ,  5000. ,     3.8],
       [  103. ,    22. , 45000. ,  1000. ,     4.2],
       [  104. ,    28. , 52000. ,  3000. ,     4. ],
       [  105. ,    35. , 75000. ,  7000. ,     3.5],
       [  106. ,    26. , 48000. ,  1500. ,     4.7],
       [  107. ,    40. , 80000. , 10000. ,     3.9],
       [  108. ,    29. , 58000. ,  4000. ,     4.3]])

In [18]:
#Filter employees where salary > 50000
salary = []
salar = data[:,2]
for x in salar:
    if x > 50000:
        salary.append(x)
print(salary)

[np.float64(60000.0), np.float64(52000.0), np.float64(75000.0), np.float64(80000.0), np.float64(58000.0)]


In [ ]:
# Get employees with rating > 4

In [27]:
emplyy = data[data[:,4]>4][:4]
emplyy

array([[1.01e+02, 2.50e+01, 5.00e+04, 2.00e+03, 4.50e+00],
       [1.03e+02, 2.20e+01, 4.50e+04, 1.00e+03, 4.20e+00],
       [1.06e+02, 2.60e+01, 4.80e+04, 1.50e+03, 4.70e+00],
       [1.08e+02, 2.90e+01, 5.80e+04, 4.00e+03, 4.30e+00]])

In [29]:
for x in data:
    if x[4]>4:
        print(x)

[1.01e+02 2.50e+01 5.00e+04 2.00e+03 4.50e+00]
[1.03e+02 2.20e+01 4.50e+04 1.00e+03 4.20e+00]
[1.06e+02 2.60e+01 4.80e+04 1.50e+03 4.70e+00]
[1.08e+02 2.90e+01 5.80e+04 4.00e+03 4.30e+00]


In [30]:
np.set_printoptions(suppress=True)
print(result)

[[  101.     25.  50000.   2000.      4.5]
 [  103.     22.  45000.   1000.      4.2]
 [  106.     26.  48000.   1500.      4.7]
 [  108.     29.  58000.   4000.      4.3]]


In [32]:
# Find total salary payout
payout = np.sum(data[:,2])
print(payout)

468000.0


In [33]:
# Sort dataset by salary (ascending)
collection = data[:,2]
reslt = np.sort(collection)
print(reslt)

[45000. 48000. 50000. 52000. 58000. 60000. 75000. 80000.]


In [36]:
sort_data = data[data[:-2].argsort()]
print(sort_data)

[[[  105.     35.  75000.   7000.      3.5]
  [  102.     30.  60000.   5000.      3.8]
  [  101.     25.  50000.   2000.      4.5]
  [  104.     28.  52000.   3000.      4. ]
  [  103.     22.  45000.   1000.      4.2]]

 [[  105.     35.  75000.   7000.      3.5]
  [  102.     30.  60000.   5000.      3.8]
  [  101.     25.  50000.   2000.      4.5]
  [  104.     28.  52000.   3000.      4. ]
  [  103.     22.  45000.   1000.      4.2]]

 [[  105.     35.  75000.   7000.      3.5]
  [  102.     30.  60000.   5000.      3.8]
  [  101.     25.  50000.   2000.      4.5]
  [  104.     28.  52000.   3000.      4. ]
  [  103.     22.  45000.   1000.      4.2]]

 [[  105.     35.  75000.   7000.      3.5]
  [  102.     30.  60000.   5000.      3.8]
  [  101.     25.  50000.   2000.      4.5]
  [  104.     28.  52000.   3000.      4. ]
  [  103.     22.  45000.   1000.      4.2]]

 [[  105.     35.  75000.   7000.      3.5]
  [  102.     30.  60000.   5000.      3.8]
  [  101.     25.  50000

In [37]:
#Calculate net salary
data

array([[  101. ,    25. , 50000. ,  2000. ,     4.5],
       [  102. ,    30. , 60000. ,  5000. ,     3.8],
       [  103. ,    22. , 45000. ,  1000. ,     4.2],
       [  104. ,    28. , 52000. ,  3000. ,     4. ],
       [  105. ,    35. , 75000. ,  7000. ,     3.5],
       [  106. ,    26. , 48000. ,  1500. ,     4.7],
       [  107. ,    40. , 80000. , 10000. ,     3.9],
       [  108. ,    29. , 58000. ,  4000. ,     4.3]])

In [39]:
cal_salary = data[:,2]
cal_bonus = data[:,3]
cal = cal_salary+cal_bonus
print(cal)

[52000. 65000. 46000. 55000. 82000. 49500. 90000. 62000.]


In [42]:
result = max(cal)
result

np.float64(90000.0)

In [45]:
new_reult = []
for x in data:
    if x[1] < 30 and x[4] > 4:
        new_reult.append(x)
print(new_reult)

[array([  101. ,    25. , 50000. ,  2000. ,     4.5]), array([  103. ,    22. , 45000. ,  1000. ,     4.2]), array([  106. ,    26. , 48000. ,  1500. ,     4.7]), array([  108. ,    29. , 58000. ,  4000. ,     4.3])]


In [46]:
new_reult

[array([  101. ,    25. , 50000. ,  2000. ,     4.5]),
 array([  103. ,    22. , 45000. ,  1000. ,     4.2]),
 array([  106. ,    26. , 48000. ,  1500. ,     4.7]),
 array([  108. ,    29. , 58000. ,  4000. ,     4.3])]

In [48]:
slray_ = data[:-3]
bouns_ = data[:-4]
rslt_final = np.corrcoef(slray_ , bouns_)
rslt_final

array([[1.        , 0.99906495, 0.9998458 , 0.99984646, 0.99857405,
        1.        , 0.99906495, 0.9998458 , 0.99984646],
       [0.99906495, 1.        , 0.99815169, 0.99966914, 0.99994836,
        0.99906495, 1.        , 0.99815169, 0.99966914],
       [0.9998458 , 0.99815169, 1.        , 0.9993846 , 0.99748263,
        0.9998458 , 0.99815169, 1.        , 0.9993846 ],
       [0.99984646, 0.99966914, 0.9993846 , 1.        , 0.99935614,
        0.99984646, 0.99966914, 0.9993846 , 1.        ],
       [0.99857405, 0.99994836, 0.99748263, 0.99935614, 1.        ,
        0.99857405, 0.99994836, 0.99748263, 0.99935614],
       [1.        , 0.99906495, 0.9998458 , 0.99984646, 0.99857405,
        1.        , 0.99906495, 0.9998458 , 0.99984646],
       [0.99906495, 1.        , 0.99815169, 0.99966914, 0.99994836,
        0.99906495, 1.        , 0.99815169, 0.99966914],
       [0.9998458 , 0.99815169, 1.        , 0.9993846 , 0.99748263,
        0.9998458 , 0.99815169, 1.        , 0.9993846 ],


In [54]:
rati = data[:,4]


In [56]:
rati = np.where(rati < 4 , 4 , rati)
print(rati)

[4.5 4.  4.2 4.  4.  4.7 4.  4.3]


In [59]:
for x in range(len(data)):
    if data[x][4] < 4:
        data[x] = 4
print(data)
        

[[  101.     25.  50000.   2000.      4.5]
 [    4.      4.      4.      4.      4. ]
 [  103.     22.  45000.   1000.      4.2]
 [  104.     28.  52000.   3000.      4. ]
 [    4.      4.      4.      4.      4. ]
 [  106.     26.  48000.   1500.      4.7]
 [    4.      4.      4.      4.      4. ]
 [  108.     29.  58000.   4000.      4.3]]


In [60]:
data

array([[  101. ,    25. , 50000. ,  2000. ,     4.5],
       [    4. ,     4. ,     4. ,     4. ,     4. ],
       [  103. ,    22. , 45000. ,  1000. ,     4.2],
       [  104. ,    28. , 52000. ,  3000. ,     4. ],
       [    4. ,     4. ,     4. ,     4. ,     4. ],
       [  106. ,    26. , 48000. ,  1500. ,     4.7],
       [    4. ,     4. ,     4. ,     4. ,     4. ],
       [  108. ,    29. , 58000. ,  4000. ,     4.3]])

In [64]:
tex = (data[:,2] *0.10).reshape(-1 , 1)
new_data = np.column_stack((data , tax))
print(new_data)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 8 and the array at index 1 has size 1

In [65]:
tax = (data[:, 2] * 0.10).reshape(-1, 1)
data = np.hstack((data, tax))

print(data)

[[  101.     25.  50000.   2000.      4.5  5000. ]
 [    4.      4.      4.      4.      4.      0.4]
 [  103.     22.  45000.   1000.      4.2  4500. ]
 [  104.     28.  52000.   3000.      4.   5200. ]
 [    4.      4.      4.      4.      4.      0.4]
 [  106.     26.  48000.   1500.      4.7  4800. ]
 [    4.      4.      4.      4.      4.      0.4]
 [  108.     29.  58000.   4000.      4.3  5800. ]]


In [66]:
data

array([[  101. ,    25. , 50000. ,  2000. ,     4.5,  5000. ],
       [    4. ,     4. ,     4. ,     4. ,     4. ,     0.4],
       [  103. ,    22. , 45000. ,  1000. ,     4.2,  4500. ],
       [  104. ,    28. , 52000. ,  3000. ,     4. ,  5200. ],
       [    4. ,     4. ,     4. ,     4. ,     4. ,     0.4],
       [  106. ,    26. , 48000. ,  1500. ,     4.7,  4800. ],
       [    4. ,     4. ,     4. ,     4. ,     4. ,     0.4],
       [  108. ,    29. , 58000. ,  4000. ,     4.3,  5800. ]])

In [71]:
sore_Data = data[data[:,2].argsort()[::-1]]
top = sore_Data[:3]
print(top)

[[  107.     40.  80000.  10000.      3.9]
 [  105.     35.  75000.   7000.      3.5]
 [  102.     30.  60000.   5000.      3.8]]


In [73]:
result = data[data[:,2].argsort()[::-1]]
print(result)

[[  107.     40.  80000.  10000.      3.9]
 [  105.     35.  75000.   7000.      3.5]
 [  102.     30.  60000.   5000.      3.8]
 [  108.     29.  58000.   4000.      4.3]
 [  104.     28.  52000.   3000.      4. ]
 [  101.     25.  50000.   2000.      4.5]
 [  106.     26.  48000.   1500.      4.7]
 [  103.     22.  45000.   1000.      4.2]]


In [81]:
advance = []
for x in data:
    if x[4] > 4:
        print('Good' , x)
    elif x>[4] > 3.5:
        print('avg' , x)
    else :
        print('low' , x)
    advance.append(x)
print(advance)

Good [  101.     25.  50000.   2000.      4.5]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

[(101, 'avg'),
 (102, 'avg'),
 (103, 'avg'),
 (104, 'avg'),
 (105, 'avg'),
 (106, 'avg'),
 (107, 'avg'),
 (108, 'avg')]

[(101, 'Good'), (102, 'Average'), (103, 'Good'), (104, 'Average'), (105, 'Average'), (106, 'Good'), (107, 'Average'), (108, 'Good')]
